### ISSUE TITLE
Is there a way to run data-driven tests parallel ?

### ISSUE THREAD

**Issue by liqin198725** [fluentsoftware/data-driven#10]
Data-driven is very useful for testing a bunch of data, but if the tests can be running in parallel will save a lot of time. Is there a way to do that?

**Comment by mjtodd** [comment]
I'm not aware of any way to do this with mocha. There is some discussion here on why parallel tests is not supported by mocha - https://github.com/mochajs/mocha/issues/98

**Comment by liqin198725** [comment]
Thanks for the reply,

I just found this https://github.com/mochajs/mocha/pull/849 , if combine this with data-driven, somehow the case can be run parallel.

**Comment by liqin198725** [comment]
:(  you are right, mocha cannot do this by itself
