### ISSUE TITLE
Dynamic scenario data doesn't work

### ISSUE THREAD

**Issue by antony** [fluentsoftware/data-driven#13]
If I want to build data dynamically, such as a series of db insertions where i later grab the database id, or the result of a promise, it isn't possible with this library.

It seems that because data has to be defined outside the 'it' clause, it is solidified before any before methods can modify the data.

**Comment by mjtodd** [comment]
Hi, and thanks for this feedback. That's not really a use case that I saw for data-driven. With data-drive, my expectation for the tests would be that the inputs to the tests, or scenarios are known up front. data-driven then allows a series of parameterised tests based on that input.

I wouldn't see the definition of tests coming from a database. That's not to say that the test setup for each test couldn't involve inserting into the database i.e. have some tests parameterised using data-driven that all need to insert data asynchronously into the db before executing the function under test.

Does this make sense? I'm happy to chat about your specific use case in more detail / have a call if that's useful to you

**Comment by sakshinagpal** [comment]
Any update on this issue.

**Comment by mjtodd** [comment]
Hi, no update other than my comment above. I'm happy to talk through your use case with you though if that would be useful?

**Comment by antony** [comment]
Sorry - so many PRs, forgot to get back to you on this!

I don't remember my exact scenario now, but as I'm using promises to save my data, I actually wanted to cycle through the saved records (dynamically generated dates, ids, etc) which isn't possible when the scenarios need to be set up pre-test.

Thanks for the offer of a chat / call - I've worked around it by now by modifying the scenario data within my test - but if I run into it again i'll drop you a message.
