### ISSUE TITLE
mocha pending functions don't work

### ISSUE THREAD

**Issue by smlgbl** [fluentsoftware/data-driven#2]
When using data-driven, the mocha functions like it.only() and it.skip() don't work.

``` javascript
it.skip("Add an offer", function(data, done){
  ^  
  TypeError: Object function (title, f) {

    for (var key in testData) {
      title = title.replace('{'+key+'}',testData[key])
    }  

    var testFn = f.length < 2 ?  
      function() {
        f(testData)
      } :  
      function(done) {
        f(testData,done)
      }  

  mochaIt(title, testFn)
  } has no method 'skip' 
```

**Comment by dwbruhn** [comment]
Hi @mjtodd, just curious what the resolution was. I'm having the same problem:

`TypeError: it.only is not a function`

**Comment by antony** [comment]
Hi @dwbruhn - in my case, I've found the constant need to replicate mocha's API enough to drop the library entirely. It's a great library, but it's now trivial to implement your own solution, especially with the advent of > es2015:

```
const scenarios = [
  { description: 'add four', var1: 1, var2: 4, expected: 5 },
  { description: 'add seven', var1: 2, var2: 7, expected: 9 },
]

scenarios.forEach(({ description, var1, var2, expected }) => {
  it(1should ${scenario}`, () => {
    expect(var1 + var2).to.equal(expected)
  })
})
```

That way, you can pretty much do what you want.
