### ISSUE TITLE
Get test data before test-driven method call

### ISSUE THREAD

**Issue by riaan53** [fluentsoftware/data-driven#8]
Hi,

Thank you for this cool lib!

One question. I need to get my test data array in a async before function. How can I do it with this library?

```js
var data_driven = require('data-driven')
var assert = require('assert');

describe('Array', function() {
  describe('#indexOf()', function(){
    this.devices = [];
    var self = this;
    
    before(function(done) {
      getAllConnectedDevices(function(devices) {
        self.devices = devices;
        done();
      });
    })

    data_driven(self.devices, function() {
        it('should return -1 when the value is not present when searching for {os}', function(ctx, done){
            console.log('asasd');
            assert.equal(-1, [1,2,3].indexOf(ctx.value));
            done();
        })
    })
  })
})

```

self.devices is always empty like it is above.

Thanks!

Regards,
Riaan

**Comment by mjtodd** [comment]
There isn't currently any ability for the test data array to be retrived async. The library was intended for in-line variant test data, e.g. testing a function with a number of different parameters. You could of course load data synchronously from disk too if you needed to.

Can your test data be retrieved synchronously? If not, then it's not something that is supported at the moment, though it's an interesting idea

**Comment by riaan53** [comment]
Ok cool. Thank you for the reply. 

Unfortunately it will have to be asynchronous because its over websocket connections to iOS and Android devices.

Regards,
Riaan
